In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_excel("data for discriminanat analysis.xlsx",sheet_name= "Sheet2")

In [ ]:
data.head()

eligibility score  age  year_emp  income  cred_debt  other_debt
0                5.5   47        22      81       1.51        2.95
1                3.6   40        22      95       0.63        2.79
2                3.4   35        16      36       0.18        1.05
3                0.4   43        16      89       0.16        0.20
4               12.8   47        26     100       4.58        8.22

In [ ]:
data['Target_Variable'] = np.where(data['eligibility score'] < 10, 'No', 'Yes')

In [ ]:
data.head()

eligibility score  age  year_emp  income  cred_debt  other_debt  \
0                5.5   47        22      81       1.51        2.95   
1                3.6   40        22      95       0.63        2.79   
2                3.4   35        16      36       0.18        1.05   
3                0.4   43        16      89       0.16        0.20   
4               12.8   47        26     100       4.58        8.22   

  Target_Variable  
0              No  
1              No  
2              No  
3              No  
4             Yes

In [ ]:
data_no = data[data["eligibility score"]<10]

In [ ]:
data_no.head()

eligibility score  age  year_emp  income  cred_debt  other_debt  \
0                5.5   47        22      81       1.51        2.95   
1                3.6   40        22      95       0.63        2.79   
2                3.4   35        16      36       0.18        1.05   
3                0.4   43        16      89       0.16        0.20   
6                4.5   35        13      35       0.43        1.14   

  Target_Variable  
0              No  
1              No  
2              No  
3              No  
6              No

In [ ]:
data_yes = data[data["eligibility score"]>10]

In [ ]:
data_yes.head()

eligibility score  age  year_emp  income  cred_debt  other_debt  \
4                12.8   47        26     100       4.58        8.22   
7                10.9   36        16      32       0.54        2.94   
8                15.8   49        14      63       0.94        9.02   
13               12.0   48        17     113       3.38       10.18   
20               16.5   38        21      58       4.58        4.99   

   Target_Variable  
4              Yes  
7              Yes  
8              Yes  
13             Yes  
20             Yes

# 1st

In [ ]:
if ((abs(data_yes["age"].mean()-55))<(abs(data_no["age"].mean()-55))):
   print("Yes")
else :
   print("No")

Yes


# 2nd

In [ ]:
df = data_yes.copy()

In [ ]:
df.drop("eligibility score", inplace = True, axis = 1)
df.drop("Target_Variable", inplace = True, axis = 1)

In [ ]:
l = []
for i in df.columns:
    l.append(df[i].mean())

In [ ]:
l

[34.958333333333336,
 8.791666666666666,
 43.208333333333336,
 2.9343750000000006,
 4.343125]

In [ ]:
k = [55,11,77,2.5,3]

In [ ]:
p =list(np.subtract(l,k))
p

[-20.041666666666664,
 -2.208333333333334,
 -33.791666666666664,
 0.4343750000000006,
 1.3431249999999997]

In [ ]:
def square(list):
    return [i ** 2 for i in list]

In [ ]:
square_value = square(p)
square_value

[401.66840277777766,
 4.876736111111113,
 1141.8767361111109,
 0.18868164062500054,
 1.8039847656249992]

In [ ]:
total = 0
for ele in range(0, len(square_value)):
    total = total + square_value[ele]

In [ ]:
total

1550.4145414062496

In [ ]:
from math import sqrt

In [ ]:
yes_value = sqrt(total)
yes_value

39.375303699225604

In [ ]:
df1 = data_no.copy()

In [ ]:
df1.drop("eligibility score", inplace = True, axis = 1)
df1.drop("Target_Variable", inplace = True, axis = 1)

In [ ]:
f = []
for i in df1.columns:
    f.append(df1[i].mean())

In [ ]:
g =list(np.subtract(f,k))

In [ ]:
square_value_no = square(g)
square_value_no

[462.671664744329,
 13.733564013840832,
 936.8400615148021,
 2.4704442906574395,
 2.0063889273356397]

In [ ]:
total_no = 0
for ele in range(0, len(square_value_no)):
    total_no = total_no + square_value_no[ele]

In [ ]:
total_no

1417.722123490965

In [ ]:
no_value = sqrt(total_no)
no_value

37.652650949049594

In [ ]:
if no_value < yes_value:
    print("No")
else :
    print("Yes")

No


# 3rd

In [ ]:
vaibhav= df.copy()

In [ ]:
vaibhav.head()

age  year_emp  income  cred_debt  other_debt
4    47        26     100       4.58        8.22
7    36        16      32       0.54        2.94
8    49        14      63       0.94        9.02
13   48        17     113       3.38       10.18
20   38        21      58       4.58        4.99

In [ ]:
covmat=vaibhav.cov()
covmat

age    year_emp      income  cred_debt  other_debt
age          59.530142   22.076241  108.306738   5.576782    9.180559
year_emp     22.076241   44.934397  125.618794   9.993910   11.764282
income      108.306738  125.618794  643.359929  50.731410   58.063165
cred_debt     5.576782    9.993910   50.731410   9.133468    6.899197
other_debt    9.180559   11.764282   58.063165   6.899197    8.883090

In [ ]:
covmat_inv= np.linalg.inv(covmat)

In [ ]:
covmat_inv = abs(covmat_inv)
covmat_inv

array([[0.02542289, 0.00108523, 0.00483657, 0.0179282 , 0.00714765],
       [0.00108523, 0.04919253, 0.00892219, 0.00170581, 0.00703243],
       [0.00483657, 0.00892219, 0.00653079, 0.00971439, 0.0183282 ],
       [0.0179282 , 0.00170581, 0.00971439, 0.28638653, 0.17971758],
       [0.00714765, 0.00703243, 0.0183282 , 0.17971758, 0.38865428]])

In [ ]:
mat=np.asmatrix(covmat_inv)
mat.shape

(5, 5)

In [ ]:
mat

matrix([[0.02542289, 0.00108523, 0.00483657, 0.0179282 , 0.00714765],
        [0.00108523, 0.04919253, 0.00892219, 0.00170581, 0.00703243],
        [0.00483657, 0.00892219, 0.00653079, 0.00971439, 0.0183282 ],
        [0.0179282 , 0.00170581, 0.00971439, 0.28638653, 0.17971758],
        [0.00714765, 0.00703243, 0.0183282 , 0.17971758, 0.38865428]])

In [ ]:
first=np.asmatrix(np.array(p))
first.shape

(1, 5)

In [ ]:
first = abs(first)
first

matrix([[20.04166667,  2.20833333, 33.79166667,  0.434375  ,  1.343125  ]])

In [ ]:
third = np.transpose(first)
third.shape

(5, 1)

In [ ]:
third

matrix([[20.04166667],
        [ 2.20833333],
        [33.79166667],
        [ 0.434375  ],
        [ 1.343125  ]])

In [ ]:
m1=np.dot(first,mat)

In [ ]:
m1, m1.shape

(matrix([[0.69273699, 0.44206548, 0.36615887, 1.05712565, 1.37819722]]),
 (1, 5))

In [ ]:
m2 = np.dot(m1,third)

In [ ]:
m2

matrix([[29.54323048]])

In [ ]:
kushagra = df1.copy()

In [ ]:
kushagra.head()

age  year_emp  income  cred_debt  other_debt
0   47        22      81       1.51        2.95
1   40        22      95       0.63        2.79
2   35        16      36       0.18        1.05
3   43        16      89       0.16        0.20
6   35        13      35       0.43        1.14

In [ ]:
covmat_no=kushagra.cov()
covmat_no

age    year_emp       income  cred_debt  other_debt
age          62.454902   24.412941   148.503922   2.447682    4.949835
year_emp     24.412941   39.251765   150.982353   3.623929    3.270541
income      148.503922  150.982353  1076.563137  37.745306   28.829988
cred_debt     2.447682    3.623929    37.745306   2.687835    1.026812
other_debt    4.949835    3.270541    28.829988   1.026812    1.933803

In [ ]:
covmat_inv_no= np.linalg.inv(covmat_no)
covmat_inv_no= abs(covmat_inv_no)
covmat_inv_no

array([[0.02819034, 0.00156262, 0.00493096, 0.05538861, 0.02541162],
       [0.00156262, 0.06441249, 0.0126076 , 0.07515492, 0.043116  ],
       [0.00493096, 0.0126076 , 0.00587024, 0.05078231, 0.02660762],
       [0.05538861, 0.07515492, 0.05078231, 0.93697069, 0.00930879],
       [0.02541162, 0.043116  , 0.02660762, 0.00930879, 0.91086127]])

In [ ]:
mat_no=np.asmatrix(covmat_inv_no)
mat_no.shape

(5, 5)

In [ ]:
mat_no

matrix([[0.02819034, 0.00156262, 0.00493096, 0.05538861, 0.02541162],
        [0.00156262, 0.06441249, 0.0126076 , 0.07515492, 0.043116  ],
        [0.00493096, 0.0126076 , 0.00587024, 0.05078231, 0.02660762],
        [0.05538861, 0.07515492, 0.05078231, 0.93697069, 0.00930879],
        [0.02541162, 0.043116  , 0.02660762, 0.00930879, 0.91086127]])

In [ ]:
first_no=np.asmatrix(np.array(g))
first_no.shape

(1, 5)

In [ ]:
first_no = abs(first_no)
first_no

matrix([[21.50980392,  3.70588235, 30.60784314,  1.57176471,  1.41647059]])

In [ ]:
third_no = np.transpose(first_no)
third.shape

(5, 1)

In [ ]:
third_no

matrix([[21.50980392],
        [ 3.70588235],
        [30.60784314],
        [ 1.57176471],
        [ 1.41647059]])

In [ ]:
d1=np.dot(first_no,mat_no)

In [ ]:
d2 = np.dot(d1,third_no)

In [ ]:
d2

matrix([[47.02783437]])

In [ ]:
no1 = sqrt(d2)
no1

6.857684329645471

In [ ]:
yes1 = sqrt(m2)
yes1

5.435368476890771

In [ ]:
if yes1< no1:
    print("Yes")
else:
    print("No")

Yes


# 4th

In [ ]:
data_no.head()

eligibility score  age  year_emp  income  cred_debt  other_debt  \
0                5.5   47        22      81       1.51        2.95   
1                3.6   40        22      95       0.63        2.79   
2                3.4   35        16      36       0.18        1.05   
3                0.4   43        16      89       0.16        0.20   
6                4.5   35        13      35       0.43        1.14   

  Target_Variable  
0              No  
1              No  
2              No  
3              No  
6              No

In [ ]:
bhavay = data_no.copy()

In [ ]:
bhavay.drop("Target_Variable", inplace = True, axis = 1)

In [ ]:
bhavay.head()

eligibility score  age  year_emp  income  cred_debt  other_debt
0                5.5   47        22      81       1.51        2.95
1                3.6   40        22      95       0.63        2.79
2                3.4   35        16      36       0.18        1.05
3                0.4   43        16      89       0.16        0.20
6                4.5   35        13      35       0.43        1.14

In [ ]:
from statsmodels.formula.api import ols
import statsmodels.api as sm

In [ ]:
X = bhavay.drop("eligibility score", axis = 1)
X.head()

age  year_emp  income  cred_debt  other_debt
0   47        22      81       1.51        2.95
1   40        22      95       0.63        2.79
2   35        16      36       0.18        1.05
3   43        16      89       0.16        0.20
6   35        13      35       0.43        1.14

In [ ]:
y = bhavay[["eligibility score"]]
y.head()

eligibility score
0                5.5
1                3.6
2                3.4
3                0.4
6                4.5

In [ ]:
x = sm.add_constant(X)
est = sm.OLS(y,x).fit()
est.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:      eligibility score   R-squared:                       0.669
Model:                            OLS   Adj. R-squared:                  0.632
Method:                 Least Squares   F-statistic:                     18.21
Date:                Fri, 13 Jan 2023   Prob (F-statistic):           7.62e-10
Time:                        11:55:32   Log-Likelihood:                -96.433
No. Observations:                  51   AIC:                             204.9
Df Residuals:                      45   BIC:                             216.5
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          7.9457      1.121      7.086      0.000       5.687      10.204
age           -0.0799      0.041     -1.971      0.055      -0.162       0.002
year_emp       0.0052      0.061      0.085      0.933      -0.118       0.129
income        -0.0748      0.018     -4.043      0.000      -0.112      -0.038
cred_debt      0.9796      0.234      4.193      0.000       0.509       1.450
other_debt     1.7420      0.230      7.563      0.000       1.278       2.206
==============================================================================
Omnibus:                        1.382   Durbin-Watson:                   1.968
Prob(Omnibus):                  0.501   Jarque-Bera (JB):                1.196
Skew:                          -0.367   Prob(JB):                        0.550
Kurtosis:                       2.846   Cond. No.                         306.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [ ]:
k

[55, 11, 77, 2.5, 3]

In [ ]:
no2 = 7.9457+(77*-0.0748)+(2.5*0.9796)+(1.7420*3)
no2

9.8611

In [ ]:
data_yes.head()

eligibility score  age  year_emp  income  cred_debt  other_debt  \
4                12.8   47        26     100       4.58        8.22   
7                10.9   36        16      32       0.54        2.94   
8                15.8   49        14      63       0.94        9.02   
13               12.0   48        17     113       3.38       10.18   
20               16.5   38        21      58       4.58        4.99   

   Target_Variable  
4              Yes  
7              Yes  
8              Yes  
13             Yes  
20             Yes

In [ ]:
ishika = data_yes.copy()

In [ ]:
ishika.drop("Target_Variable", axis = 1,inplace = True)
ishika.head()

eligibility score  age  year_emp  income  cred_debt  other_debt
4                12.8   47        26     100       4.58        8.22
7                10.9   36        16      32       0.54        2.94
8                15.8   49        14      63       0.94        9.02
13               12.0   48        17     113       3.38       10.18
20               16.5   38        21      58       4.58        4.99

In [ ]:
X1 = ishika.drop("eligibility score", axis = 1)
X1.head()

age  year_emp  income  cred_debt  other_debt
4    47        26     100       4.58        8.22
7    36        16      32       0.54        2.94
8    49        14      63       0.94        9.02
13   48        17     113       3.38       10.18
20   38        21      58       4.58        4.99

In [ ]:
y1 = ishika[["eligibility score"]]
y1.head()

eligibility score
4                12.8
7                10.9
8                15.8
13               12.0
20               16.5

In [ ]:
x = sm.add_constant(X1)
est = sm.OLS(y1,x).fit()
est.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:      eligibility score   R-squared:                       0.848
Model:                            OLS   Adj. R-squared:                  0.829
Method:                 Least Squares   F-statistic:                     46.73
Date:                Fri, 13 Jan 2023   Prob (F-statistic):           4.32e-16
Time:                        12:00:49   Log-Likelihood:                -111.60
No. Observations:                  48   AIC:                             235.2
Df Residuals:                      42   BIC:                             246.4
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         15.6561      1.847      8.475      0.000      11.928      19.384
age           -0.0345      0.062     -0.560      0.578      -0.159       0.090
year_emp      -0.0302      0.086     -0.353      0.726      -0.203       0.142
income        -0.2326      0.031     -7.458      0.000      -0.296      -0.170
cred_debt      1.2656      0.207      6.129      0.000       0.849       1.682
other_debt     1.9614      0.241      8.153      0.000       1.476       2.447
==============================================================================
Omnibus:                       19.252   Durbin-Watson:                   1.889
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               26.744
Skew:                           1.339   Prob(JB):                     1.56e-06
Kurtosis:                       5.491   Cond. No.                         297.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [ ]:
k

[55, 11, 77, 2.5, 3]

In [ ]:
yes2 = 15.6561+(77*-0.2326)+(2.5*1.2656)+(1.9614*3)
yes2

6.7941

In [ ]:
if yes2< no2:
    print("Yes")
else:
    print("No")

Yes
